model:
  source_path: "/home/ubuntu/datasets/ScanNet/processed/scene0000_01"
  model_path: "outputs/scannet/scene0000_01"
  init_type: ply # Usa la nube de puntos que generamos
  mask_subdir: "sam" # Asumiendo que las generaste con ese nombre
opt:
  iterations: 40000
  position_lr_max_steps: 40000
  position_lr_init: 1.6e-5
  lambda_depth: 0.1
  lambda_normal: 0.00
  densify_until_iter: 25000
  densify_grad_threshold: 0.0003
  random_background: true
  random_background_features: true
  inst2d_lambda: 0.2
  var_lambda: 0.1
  lambda_thin: 0.0
cluster:
  enabled: true
  min_size: 15
  min_samples: 16
lang:
  enabled: true
  model: masqclip
  topk: 5
  levels: 3 # 0 for using full image with masqclip
  ratio: 0.3
  dynamic_ratio: true
