model:
  eval: true
  init_points: 750000
  mask_subdir: sam
  resolution: 2
  num_frames: 300
opt:
  densify_grad_threshold: 3.5e-4
  random_background: true
  random_background_features: true
  inst2d_lambda: 0.1
  var_lambda: 0.5
cluster:
  enabled: true
  min_size: 32
  min_samples: 16
lang:
  enabled: true
  model: masqclip
  topk: 5
  levels: 3 # 0 for using full image with masqclip
  ratio: 0.3
  dynamic_ratio: true
export_scannetpp:
  enabled: true
  use_segments: true
